include $(GOROOT)/src/Make.inc

TARG=github.com/mikejs/gomongo/mongo
GOFILES=\
	main.go\
\
	connection.go\
	database.go\
	collection.go\
	cursor.go\
	message.go\
	bson.go\
	bson-struct.go\

include $(GOROOT)/src/Make.pkg

